FROM centos:7
WORKDIR /
RUN yum -y update && yum -y install epel-release && yum repolist

RUN yum install -y centos-release-scl
RUN yum install -y devtoolset-9

RUN echo "source /opt/rh/devtoolset-9/enable" >> /etc/bashrc
SHELL ["/bin/bash", "--login", "-c"]

RUN yum -y install cmake3 make imake autoconf automake pkgconfig libtool gtest gtest-devel csv
RUN yum -y install git wget subversion openssh-clients openssl-devel bzip2

RUN yum -y install redhat-lsb-core  mysql-devel cfitsio-devel graphviz-devel libuuid-devel avahi-compat-libdns_sd-devel openldap-devel numpy  readline-devel R-devel R-Rcpp-devel R-RInside-devel yaml-cpp

RUN yum -y install xorg-x11-utils
RUN yum -y install libXt-devel libXpm-devel libXft-devel libXext-devel libxi-dev

RUN yum -y install mesa-libGLU-devel mesa-libGLw glew-devel motif-devel libpng-devel libjpeg-turbo-devel ftgl-devel

RUN yum -y install libxml2-devel gmp-devel gsl-devel log4cpp-devel bzip2-devel pcre-devel xz-devel zlib-devel freetype-devel fftw-devel blas-devel lapack-devel lz4-devel xz-devel libgtest-dev

RUN yum -y install xerces-c-devel qt5-qtbase-devel build-essential libexpat1-dev libxmu-dev libxerces-c-dev cmake-curses-gui qt5-default qtbase5-dev zlib1g-dev libmotif-dev

RUN yum -y install vim nano gdb csh tcsh ed quota patch parallel python-devel
 
RUN ln -s /usr/bin/cmake3 /usr/bin/cmake

ENV PATH="/opt/rh/devtoolset-9/root/bin:$PATH"

RUN sed -i "s/alias/#alias/g" /root/.bashrc
RUN sed -i "s/alias/#alias/g" /root/.cshrc
RUN sed -i "s/alias/#alias/g" /root/.tcshrc

ENV GTEST_MAIN_LIBRARY="/usr/lib64"
ENV GTEST_LIBRARY="/usr/lib64"
ENV GTEST_INCLUDE_DIR="/usr/include"
