FROM jnugent42/wagasci_data_handling:centos_7 AS wagana_build
WORKDIR /

RUN mkdir -p ~/.ssh/
RUN ssh-keyscan git.t2k.org > ~/.ssh/known_hosts

ENV BOOST_ROOT="${BOOSTDIR}/boost_${BOOSTVERS}_sources" 
RUN mkdir -p /opt/wagasci_ana

WORKDIR /opt/wagasci_ana 
RUN --mount=type=ssh git clone git@git.t2k.org:wagasci_babymind/wagasci-babymind-mctruth-based-study.git WagasciMCTruth
WORKDIR WagasciMCTruth
RUN mkdir /opt/wagasci_ana/WagasciMCTruth/build
WORKDIR /opt/wagasci_ana/WagasciMCTruth/build
RUN cmake /opt/wagasci_ana/WagasciMCTruth \
  -DB2MC_PATH=/opt/wagasci_mc/WagasciMC \
  -DEVENT_DISPLAY_PATH=/opt/wagasci_mc/WagasciED \
  -DBoost_INCLUDE_DIR=/opt/BOOST/boost_1_73_0/include \
  -DCMAKE_INSTALL_PREFIX=/opt/wagasci_ana/WagasciMCTruth
RUN make -j${nproc}

WORKDIR /opt/wagasci_ana
RUN --mount=type=ssh git clone git@git.t2k.org:wagasci_babymind/wagasci-babymind-xsec-analysis.git WagasciXsec
WORKDIR /opt/wagasci_ana/WagasciXsec
RUN git checkout v0.0.0
WORKDIR /opt/wagasci_ana/WagasciXsec/external
RUN git clone https://github.com/gipert/progressbar.git
RUN mkdir /opt/wagasci_ana/WagasciXsec/build
WORKDIR /opt/wagasci_ana/WagasciXsec/build
RUN cmake .. \
   -DCMAKE_INSTALL_PREFIX=/opt/wagasci_ana/WagasciXsec \
   -DB2MC_PATH=/opt/wagasci_mc/WagasciMC \
   -DEVENT_DISPLAY_PATH=/opt/wagasci_mc/WagasciED \
   -DGENFIT_PATH=/opt/GenFit \
   -DBoost_INCLUDE_DIR=/opt/BOOST/boost_1_73_0/include \
   -DWAGASCI_REWEIGHT_PATH=/opt/wagasci_mc/WagasciRW \
   -DWITH_T2KREWEIGHT=OFF
RUN make -j"$(nproc)" 

RUN export PATH=/opt/rh/devtoolset-9/root/usr/bin${PATH:+:${PATH}}
RUN export MANPATH=/opt/rh/devtoolset-9/root/usr/share/man:${MANPATH}
RUN export INFOPATH=/opt/rh/devtoolset-9/root/usr/share/info${INFOPATH:+:${INFOPATH}}
RUN export PCP_DIR=/opt/rh/devtoolset-9/root
RUN rpmlibdir=$(rpm --eval "%{_libdir}")

RUN if [ "$rpmlibdir" != "${rpmlibdir/lib64/}" ]; then \
rpmlibdir32=":/opt/rh/devtoolset-9/root${rpmlibdir/lib64/lib}"; \
 fi
RUN export LD_LIBRARY_PATH=/opt/rh/devtoolset-9/root$rpmlibdir$rpmlibdir32${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
RUN export LD_LIBRARY_PATH=/opt/rh/devtoolset-9/root$rpmlibdir$rpmlibdir32:/opt/rh/devtoolset-9/root$rpmlibdir/dyninst$rpmlibdir32/dyninst${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
RUN export PKG_CONFIG_PATH=/opt/rh/devtoolset-9/root/usr/lib64/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}

