# syntax=docker/dockerfile:1
FROM jnugent42/buildbox:centos_7 AS boost_build
WORKDIR /

ENV BOOSTVERS=1_73_0

RUN mkdir -p ~/.ssh/
RUN ssh-keyscan github.com > ~/.ssh/known_hosts

ENV BOOSTDIR=/opt/BOOST
RUN mkdir -p /opt/BOOST

WORKDIR /opt/BOOST
RUN wget https://boostorg.jfrog.io/artifactory/main/release/${BOOSTVERS//_/.}/source/boost_${BOOSTVERS}.tar.gz
RUN tar -xvf boost_${BOOSTVERS}.tar.gz
RUN mv "${BOOSTDIR}/boost_${BOOSTVERS}" "${BOOSTDIR}/boost_${BOOSTVERS}_sources"
WORKDIR "${BOOSTDIR}/boost_${BOOSTVERS}_sources"

RUN CC="$(command -v gcc)" CXX="$(command -v g++)" \
    ./bootstrap.sh --prefix="${BOOSTDIR}/boost_${BOOSTVERS}"
RUN  CC="$(command -v gcc)" CXX="$(command -v g++)" \
    ./b2 install

FROM jnugent42/buildbox:centos_7 AS geant_build
ENV GEANTVERS="10.6.2"
ENV GEANTSRC="/opt/geant4-sources"

WORKDIR "/opt"
RUN git clone https://github.com/Geant4/geant4.git "/opt/geant4-sources"
WORKDIR "/opt/geant4-sources"
RUN git checkout v${GEANTVERS}
WORKDIR "/opt"
RUN mkdir -p "/opt/geant4-${GEANTVERS}-build"
RUN mkdir -p "/opt/geant4-${GEANTVERS}"
WORKDIR "/opt/geant4-${GEANTVERS}-build"
RUN cmake \
-DCMAKE_INSTALL_PREFIX=/opt/geant4-${GEANTVERS} \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DGEANT4_USE_GDML=ON \
-DGEANT4_INSTALL_DATA=ON \
-DGEANT4_BUILD_MULTITHREADED=ON \
-DGEANT4_USE_OPENGL_X11=ON \
-DGEANT4_USE_QT=ON \
-DGEANT4_USE_XM=ON \
-DGEANT4_USE_SYSTEM_EXPAT=ON \
-DGEANT4_USE_SYSTEM_ZLIB=ON \
$GEANTSRC
RUN make -j"$(nproc)" 
RUN make install
RUN rm -rf "/opt/geant4-${GEANTVERS}-build" "/opt/geant4-sources"

FROM jnugent42/root_v6_24_06:centos_7 AS genfit_build
ENV GENFITVERS="02-00-00"
ENV GenFitDIR="/opt/GenFit"
ENV GENFITSRC="${GenFitDIR}/sources"

WORKDIR "/opt"
RUN mkdir -p "${GenFitDIR}"
RUN mkdir -p "${GenFitDIR}/${GENFITVERS}"
WORKDIR "/opt/GenFit"
RUN realpath 02-00-00
RUN mkdir -p "${GenFitDIR}/${GenFitVERS}"
RUN mkdir -p "${GenFitDIR}/${GenFitVERS}-build"
WORKDIR "${GenFitDIR}"
RUN git clone https://github.com/GenFit/GenFit.git sources
WORKDIR "${GENFITSRC}"
RUN git checkout -b v${GenFitVERS} 
WORKDIR "${GenFitDIR}"/${GenFitVERS}-build
RUN cmake -DCMAKE_INSTALL_PREFIX=$GenFitDIR/$GENFITVERS -DCMAKE_CXX_STANDARD=11  $GenFitDIR/sources
RUN cmake --build . --target install -- -j"$(nproc)"
ENV export GENFITDIR="${GenFitDIR}/${GenFitVERS}"
    
RUN rm -rf "${GenFitDIR}"/${GenFitVERS}-build

FROM jnugent42/buildbox:centos_7 AS yaml_build

WORKDIR /opt
RUN git clone https://github.com/jbeder/yaml-cpp.git yaml-cpp
RUN mkdir -p /opt/yaml-cpp/build
WORKDIR /opt/yaml-cpp/build
RUN cmake -DCMAKE_INSTALL_PREFIX=/opt/yaml-cpp -DYAML_BUILD_SHARED_LIBS=ON ..
RUN make -j"$(nproc)"
RUN make install
    
# RUN rm -rf /opt/yaml-cpp/build

FROM jnugent42/t2kreweight:centos_7
WORKDIR /

ENV BOOSTVERS=1_73_0
ENV BOOSTDIR=/opt/BOOST
COPY --from=boost_build /opt/BOOST /opt/BOOST

ENV GEANTVERS="10.6.2"
ENV GEANTSRC="/opt/geant4-sources"
COPY --from=geant_build /opt/geant4-${GEANTVERS} /opt/geant4-${GEANTVERS}
RUN echo "source /opt/geant4-${GEANTVERS}/bin/geant4.sh" >> /etc/bashrc
SHELL ["/bin/bash", "--login", "-c"]

ENV GENFITVERS="02-00-00"
ENV GenFitDIR="/opt/GenFit"
COPY --from=genfit_build $GenFitDIR/$GENFITVERS $GenFitDIR/$GENFITVERS
ENV export GENFITDIR="${GenFitDIR}/${GenFitVERS}"

ENV YAMLDIR=/opt/yaml-cpp
COPY --from=yaml_build /opt/yaml-cpp /opt/yaml-cpp
